name: Autofix

on:
  pull_request:
  push:
    branches: ['main']

permissions:
  contents: write

jobs:
  linting-and-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare
        uses: ./.github/actions/prepare

      - name: Lint
        run: npm run lint:fix

      - name: Format
        run: npm run format:fix

      - name: Commit changes
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const git = require('simple-git')();
            const changes = await git.diffSummary();
            if (changes.files.length > 0) {
              await git.add('./*');
              await git.commit('chore: apply automated fixes');
              await git.push();
            }
