name: autofix.ci # needed to securely identify the workflow

on:
  pull_request:
  push:
    branches: ['main']

permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Prepare
        uses: ./.github/actions/prepare

      - name: Lint
        run: npm run lint:fix

      - name: Format
        run: npm run format:fix

      - uses: autofix-ci/action@ea32e3a12414e6d3183163c3424a7d7a8631ad84
        with:
          commit-message: 'chore: apply automated fixes'
